# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookshop_login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from registration_window import Ui_RegistrationWindow
from clickableLabel import ClickableLabel


class Ui_Login_Window(object):

    def __init__(self, connection):
        self.connection = connection

    def setupUi(self, Login_Window):
        Login_Window.setObjectName("MainWindow")
        Login_Window.resize(500, 350)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Login_Window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Login_Window)
        self.centralwidget.setStyleSheet("background-color:rgb(89, 89, 89);")
        self.centralwidget.setObjectName("centralwidget")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(112, 180, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)


        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("font: 63 8pt \"Segoe UI Semibold\" ")
        self.login_btn.setObjectName("login_btn")
        self.login_btn.clicked.connect(self.login)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 240, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.reg_label = ClickableLabel(self.centralwidget)
        self.reg_label.setGeometry(QtCore.QRect(290, 240, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.reg_label.setFont(font)
        self.reg_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reg_label.setObjectName("reg_label")
        self.reg_label.clicked.connect(self.registration)
        # self.reg_label.

        self.login_line = QtWidgets.QLineEdit(self.centralwidget)
        self.login_line.setGeometry(QtCore.QRect(140, 90, 250, 30))
        self.login_line.setObjectName("login_line")
        self.pass_line = QtWidgets.QLineEdit(self.centralwidget)
        self.pass_line.setGeometry(QtCore.QRect(140, 140, 250, 30))
        self.pass_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_line.setObjectName("pass_line")
        Login_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login_Window)
        QtCore.QMetaObject.connectSlotsByName(Login_Window)


    def login(self):
        login = self.login_line.text()
        password = self.pass_line.text()

        with self.connection.cursor() as cursor:
            cursor.execute("select login, pass from user;")
            lst = cursor.fetchall()

            for i in lst:
                if login == i['login'] and password == i['pass']:
                    print("successfully")
                    self.show_message(text='Authorization was successful',
                                      title='Authorization')
                    break

                else:
                    self.show_message(text="Authorization was not successful",
                                      title="Authorization")
                    print("not successfully")
                    break

    def registration(self):
        try:
            self.regs = My_RegistrationWindow(connection=self.connection)
            self.regs.show()

        except Exception as ex:
            print(ex)

    def show_message(self, text, title):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(text)
        msg.setIcon(QtWidgets.QMessageBox.Warning)

        msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Окно входа"))
        self.login_btn.setText(_translate("MainWindow", "Войти"))
        self.label.setText(_translate("MainWindow", "Нет аккаунта?"))
        self.reg_label.setText(_translate("MainWindow", "Регистрация"))


class My_RegistrationWindow(QtWidgets.QMainWindow, Ui_RegistrationWindow):
    def __init__(self, connection, parent=None):
        self.connection = connection
        super(My_RegistrationWindow, self).__init__(parent)
        self.setupUi(self)

